### ISSUE TITLE
[Discord] Channel Topic Bar and Search dialog are reverted back to Discord defaults.

### ISSUE THREAD

**Issue by toor** [chrisduerr/userstyles#19]
![image](https://user-images.githubusercontent.com/26892813/32146861-a93bfe00-bcd5-11e7-9c1a-52b23eb3765e.png)

**Comment by toor** [comment]
The channel switcher also looks like it's the Discord default, however this has been the case for a week or so. Don't know whether this is a known bug or not.

**Comment by chrisduerr** [comment]
Is this on 39edb853f4cdef4d83cb4a7ed6e18c6d0eb6f953? This should already be fixed.
